package com.emil.coupnsproject.exception;

public class MissingAutoGeneratedKeyExceptionCrud extends CrudDAOException {
    public MissingAutoGeneratedKeyExceptionCrud(String msg) {
        super(msg);
    }
}
